name: results

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Initialise Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"
    - name: Install dependencies for Python ${{ matrix.python-version }}
      run: |
        poetry env use "${{ matrix.python-version }}"
        poetry install
    - name: Testing
      run: |
        poetry env info
        ERRORS=errors.txt
        for CSV in results/*.csv; do
            echo "Validating $CSV"
            echo poetry run vanjari-tools validate-csv --csv "$CSV" --errors "$ERRORS"
            if [ -f "$ERRORS" ]; then
                echo "Error: $CSV has errors"
                cat "$ERRORS"
                exit 1
            fi
        done
